CREATE TABLE User
(
Id INTEGER AUTO_INCREMENT NOT NULL,
Name VARCHAR(100) NOT NULL,
FirstName VARCHAR(100) NOT NULL,
Email VARCHAR(150) NOT NULL,
Password VARCHAR(50) NOT NULL,
Adress TEXT,
Type	VARCHAR(1),
Places	VARCHAR(1),
Radius	SMALLINT,
PRIMARY KEY (Id)
);